version: '3'

services:           
    frontend:
        hostname: rowerovo-frontend
        build:
            context: .
            dockerfile: Dockerfile
        command: npm run dev
        volumes:
            - ./vue/:/usr/src/app
        networks:
            - proxy
networks:
    proxy:
        external: true
